### ISSUE TITLE
Creating React client with TypeScript

### ISSUE THREAD

**Issue by ShinaZin** [build-js-app/build-app#3]
I've  used `app-scripts init fullstack-react --project full --ide code --server mongo --client react
` and current fullstack config is very good, but what about react+ts client? I want to use something like  [this](https://github.com/wmonk/create-react-app-typescript). 
Or how can i migrate client to ts? Any ideas?

**Comment by erik-sytnyk** [comment]
You can use 
https://github.com/wmonk/create-react-app-typescript with
create-react-app my-app --scripts-version=react-scripts-ts
It should work with build-app setup (the only think which is required that in client folder `npm run start` is running client in dev mode and `npm run build` builds client into /build folder and with react-scripts-ts that is default setup)
Personally, I used to have TS on the server and JS on the client, so I've never tested that, let me know if that worked for you.

**Comment by ShinaZin** [comment]
It seems that replacing the content of the `/client` works. I have not tried to deploy anywhere yet. Is there any plans to add simple template for react typescript client?
