### ISSUE TITLE
Error with global dependencies

### ISSUE THREAD

**Issue by ShinaZin** [build-js-app/build-app#4]
On some systems, i get error message when using `app-scripts  deploy `or `app-scripts  install`:
```
$ app-scripts deploy -t heroku -i dev  --heroku-app simple-react
Switch to "dev" branch... done in 00.01 seconds.
Some of global dependencies should be installed/updated.
Please run following command manually and run 'install' script again.
npm install -g typescript react-scripts
```
Global dependencies are already installed, but 'apps-scripts' can't detect them:
```
$ npm list -g typescript react-scripts
D:\repos\shared\nodejs
+-- react-scripts@1.1.4
`-- typescript@2.8.1
```
Installing and updating packages did not help.
Manual installation (`npm install`) instead of the `app-script install` works, but deploying falls with same error.
How can I fix it? Maybe problem in path? 
Or how can I deploy it on Heroku manually?

**Comment by erik-sytnyk** [comment]
@ShinaZin you can remove them from global dependencies in package.json (client and server)
if they are installed globally it should work fine, you can install them as local dependencies as well

checking for global dependencies is just convenience check and is not obligatory
