### ISSUE TITLE
Change deployment target-id on heroku

### ISSUE THREAD

**Issue by ShinaZin** [build-js-app/build-app#5]
For example, I deployed my application via `app-scripts deploy -t heroku -i dev -heroku-app app1-id`. After a while, I wanted to deploy my application to `app2-id`.
But when I use `app-scripts deploy -t heroku -i dev -heroku-app app2-id`, it continues to deploy to `app1-id`. How can I change this behavior? Where does it store `app-id`?

**Comment by erik-sytnyk** [comment]
You can remove deploy folder and initialize deployment with new parameters. When using heroku deployments it pushes changes to corresponding heroku remote. Command `app-scripts deploy -t heroku -i dev -heroku-app app1-id` it creates branch 'dev' which reference remote for 'app1-id'.
